name: C/C++ CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ammaraskar/gcc-problem-matcher@master

    - name: deps
      run: sudo apt install
        asciidoctor
        bash-completion
        libdrogon-dev
        libjsoncpp-dev
        uuid-dev
        libpq-dev
        libsqlite3-dev
        libmariadb-dev
        libbrotli-dev
        libhiredis-dev
        libyaml-cpp-dev
        libtrantor-dev

    - name: configure
      run: cmake -B build
        -DCMAKE_CXX_FLAGS="-O2 -pipe -fno-plt -Wall -Wextra"
        -DCMAKE_C_FLAGS="-O2 -pipe -fno-plt -Wall -Wextra"
        -DCMAKE_BUILD_TYPE=None
        -DCMAKE_INSTALL_PREFIX=/usr
        -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON

    - name: build
      run: |
          export MAKEFLAGS=-j$(nproc)
          cmake --build build

    - name: deb
      run: |
          strip --strip-all $(find build -maxdepth 1 -executable -type f)
          cmake --build build --target package

    - uses: actions/upload-artifact@v4
      with:
        name: ubuntu_package
        path: build/*.deb
